# TP N°1 : Pipeline d'Acquisition de Données (KDD)

**Objectif :** Construire un pipeline capable de fusionner des données hétérogènes (CSV, JSON, SQL) dans un seul DataFrame Pandas.

## 1. Importation des bibliothèques nécessaires

In [1]:
import pandas as pd
import json
from sqlalchemy import create_engine
import requests
from bs4 import BeautifulSoup

## 2. Acquisition des données multi-sources

### 2.1. Données structurées : Fichier CSV

In [2]:
# Chargement du dataset Student Performance (simulé)
df_students = pd.read_csv('../data/student-mat.csv', sep=';')
print("Aperçu des données des étudiants (CSV) :")
display(df_students.head())

Aperçu des données des étudiants (CSV) :

   StudentID school sex  age  G1  G2  G3
0          1     GP   F   18  10  11  12
1          2     GP   M   17  12  13  14
2          3     GP   F   15  14  15  16
3          4     GP   M   16  15  16  17
4          5     GP   F   17  16  17  18

### 2.2. Données semi-structurées : Fichier JSON

In [3]:
# Chargement du dataset de films (simulé)
with open('../data/movies.json', 'r') as f:
    movies_data = json.load(f)
df_movies = pd.DataFrame(movies_data)
print("Aperçu des données des films (JSON) :")
display(df_movies.head())

Aperçu des données des films (JSON) :

   MovieID                  Title    Genre  StudentID
0        1             The Matrix   Sci-Fi          1
1        2  The Lord of the Rings  Fantasy          2
2        3           Pulp Fiction    Crime          3
3        4           Forrest Gump    Drama          4
4        5              Inception   Sci-Fi          5

### 2.3. Données depuis une base de données (Simulation SQL)

In [4]:
# Pour cet exercice, nous allons simuler l'extraction depuis une base de données.
# Nous allons simplement filtrer le DataFrame des étudiants comme si nous faisions une requête SQL.
df_sql_filtered = df_students[df_students['G3'] > 15].copy()
df_sql_filtered.rename(columns={'G3': 'FinalGrade'}, inplace=True)
print("Aperçu des données filtrées (simulation SQL) :")
display(df_sql_filtered.head())

Aperçu des données filtrées (simulation SQL) :

    StudentID school sex  age  G1  G2  FinalGrade
2           3     GP   F   15  14  15          16
3           4     GP   M   16  15  16          17
4           5     GP   F   17  16  17          18
9          10     GP   M   17  14  15          16
12         13     GP   F   15  14  15          16

### 2.4. Données non-structurées : Web Scraping

In [5]:
# Scraping des titres depuis la page d'accueil de Wikipedia en français
url = 'https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Accueil_principal'
response = requests.get(url)
soup = BeautifulSoup(response.content, 'html.parser')
titles = [h1.text for h1 in soup.find_all('h1')]
df_scraped = pd.DataFrame(titles, columns=['Scraped_Titles'])
print("Titres scrapés depuis Wikipedia :")
display(df_scraped.head())

Titres scrapés depuis Wikipedia :

Empty DataFrame
Columns: [Scraped_Titles]
Index: []

## 3. Fusion des données

In [6]:
# Fusionner les données des étudiants et des films
df_merged = pd.merge(df_students, df_movies, on='StudentID', how='left')
print("Aperçu des données fusionnées (étudiants et films) :")
display(df_merged.head())

Aperçu des données fusionnées (étudiants et films) :

,StudentID,school,sex,age,G1,G2,G3,MovieID,Title,Genre
0,1,GP,F,18,10,11,12,1.0,The Matrix,Sci-Fi
1,2,GP,M,17,12,13,14,2.0,The Lord of the Rings,Fantasy
2,3,GP,F,15,14,15,16,3.0,Pulp Fiction,Crime
3,4,GP,M,16,15,16,17,4.0,Forrest Gump,Drama
4,5,GP,F,17,16,17,18,5.0,Inception,Sci-Fi

## 4. Conclusion
Ce notebook a démontré un pipeline d'acquisition de données simple, en collectant et fusionnant des données de sources variées (CSV, JSON, et simulation SQL) en un seul DataFrame unifié.